### ISSUE TITLE
Acceptable asset types and durations

### ISSUE THREAD

**Issue by cboettig** [stac-extensions/forecast#2]
The current standard suggests ncdf and grib2 as recognized assets.  This is a great start but I think too narrow.  Importantly, I think neither of these formats are really cloud-optimized, i.e. GDAL VSI requests will be slower trying to extract specific regions than  cog geotif, which should also be an option?  Likewise, some forecasts will be for non-raster data, I think it would make sense to allow assets to be in formats like geoparquet, etc?  What about zarr?  Is there a reason to pre-define the acceptable asset types?  

Also, I'm a bit unclear what if anything is assumed about the dimensionality of an individual asset. i.e. does an asset have to represent a single `forecast:datetime`?  This makes sense for assets which are fundamentally 2d, like geotif or grib2, but a ncdf file (or hdf5, zarr, etc) can have arbitrary dimensions, i.e. `forecast:datetime` could be a dimension in the ncdf file, rather than serialized as metadata of separate assets.  

I think these different serialization strategies should all be supported.

**Comment by m-mohr** [comment]
This is a misunderstanding, I just wanted to list potential media types to help implementors to use the right media type but the list was neither meant to be exclusive nor complete. So this is meant to work for any file format. I've clarified this now.

For multi-dimensional data formats we may want to look at the data cube extension and make this work together with this extension? Do you have a proposal or an example that we can work with?

**Comment by m-mohr** [comment]
Closing this as the asset types were clarified and I opened another specific issue around the multi-dimensionality issue: #8
