### ISSUE TITLE
Swap reference and forecast datetime?

### ISSUE THREAD

**Issue by zakjan** [stac-extensions/forecast#7]
The spec for [datetime](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#datetime) emphasises that it should be the most useful datetime for a user to search for. It's allowed to contain a representative datetime instead of an acquisition datetime.

I'm wondering whether reference and forecast datetime could be swapped in regards to the above? I.e. forecast datetime would be a primary datetime in `datetime`, and reference datetime would be a secondary datetime e.g. in `forecast:reference_datetime`.

Also, it would improve the usability of required Collection [Temporal Extent Object](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#temporal-extent-object) in `extent.temporal`. As old forecasts are always marked as deprecated and cleaned up frequently, it would be more useful if the temporal extent contains a forecast temporal extent instead of a reference temporal extent.

**Comment by m-mohr** [comment]
When writing the spec, I was actually thinking about this "lifecycle" in https://github.com/stac-extensions/timestamps/#lifecycle, but I agree that your proposed way also make sense. Looking forward to some more opinions.

**Comment by m-mohr** [comment]
Also discussed right now in #1. This will certainly be changed.

**Comment by m-mohr** [comment]
I've updated the Readme accordingly.
