### ISSUE TITLE
Should datetime be set to null?

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/forecast#9]
If we specify the start_datetime and end_datetime, should the datetime be set to null or is there a more clever way to use it? In other domains it is often set to the center datetime between start and end, but I'm not sure whether that makes sense here. Does the start_datetime make more sense so that the datetime just mirrors that value? Otherwise, we can also keep it to be null.

**Comment by cboettig** [comment]
I may be a bit confused about `start_datetime` / `end_datetime`, (see #1) , but my current understanding is that `start_datetime` = `datetime` or otherwise that `start_datetime` = `datetime - duration` if duration is negative.

**Comment by m-mohr** [comment]
Basically copying my text from #1 with some additions for clarity:

The extension right now is meant to always use start/end_datetime if the duration is specified. The datetime is then set to null for now, but that's what we need to discuss here. Basically duration is meant to express the difference between the start and end datetimes. So basically start_datetime + duration = end_datetime. datetime itself is not set yet, but we should discuss whether we want to set it to something useful, e.g. the start_datetime. Whenever start and end datetimes are set in STAC, the individual domains that author an extension need to check what could be a good use for the datetime field as it's often still used in searches and propose how it should be used. If there's nothing that is useful, it is set to null. For example, for satellite imagery that has a long capture time, datetime is usually set to the center datetime. Here I feel like it could be an idea to set the datetime to the start_datetime, but I'm not sure.

**Comment by m-mohr** [comment]
Any further thoughts., @cboettig? I'm planning to do a pre-release in the next time.

**Comment by cboettig** [comment]
thanks, I do follow this now.  I like the convention of setting it the midpoint if that's the established convention, rather than `NULL`, such that it is still a query-able field?  

I'm not convinced that choosing the midpoint is better than the start_datetime though.  If you think about the common case of a "daily" forecast, which would really be an interval with start_datetime and end_datetime.  Many forecasts of this nature will just report an ISO 8601 date without timestamp, and  most every computational tool I know follows the convention when coercing a date to a datetime to go to the very *start*, not the midpoint.

**Comment by cboettig** [comment]
More minor, but it also just feels weird to me to say that the term is REQUIRED but can be Null.  (Maybe that's just an R thing; in R JSON is the logical equivalent of a named list, and a list whose key is set to Null is equivalent to dropping that key from the list)

**Comment by m-mohr** [comment]
Yeah, so the benefit of setting a datetime is that it is more interoperable. Not all tools can work with start and end datetimes, this is especially true when querying data. Therefore, the question is which datetime do we set for it: start, center or end datetime. center is the recommended behavior for spectral imagery, but that doesn't mean we need to do it here. This is not a choice based on what tooling does, but what is most useful for users when querying the data so that the result don't feel too unexpected. Especially for larger intervals, the center might be misleading,. My question here is which the most useful one for the "forecast domain"? If I understand you correctly, you are saying it should be the start datetime, right? I'd be happy to recommend that in the spec.

That datetime is required although it is set to null we inherit from STAC, nothing we can do about that if we don't recommend a specific other handling. But we can make this less akward by deciding to set e.g. to the start datetime instead. :-)
